name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload Artifact
      if: success()  # Only runs if the previous step (build) was successful
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact.jar
        path: target/*release.jar  # Modify this path based on your JAR file's location
