name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Create Build Folder and Add/Replace JAR
      if: success()  # Only runs if the previous step (build) was successful
      run: |
        mkdir -p build-jar  # Create 'build' directory if it doesn't exist
        cp -f target/*.jar build-jar/  # Copy the JAR file to the 'build' directory, replacing if it already exists

        cd build-jar
        git init  # Initialize a Git repository within the 'build-jar' directory
        git config --local user.email "github-actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .  # Add the contents of the 'build-jar' directory
        git commit -m "Update JAR file in build folder" || echo "No changes to commit"
        git remote add origin "https://github.com/$GITHUB_REPOSITORY"  # Set the remote repository URL
        git push --force origin HEAD:refs/heads/main  # Push the changes to the 'main' branch
