name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload Artifact
      if: success()  # Only runs if the previous step (build) was successful
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: target/*.jar  # Modify this path based on your JAR file's location

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.event.action == 'push'

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: my-artifact
        path: /tmp/my-artifact

    - name: Move Artifact to Root
      run: mv /tmp/my-artifact/target/*.jar ./

    - name: Commit Artifact to Repository
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "Add generated JAR file"
        git push
