name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Push to Branch
      if: success()  # Only runs if the previous step (build) was successful
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git checkout -b build  # Create or switch to the 'build' branch
        git add -f target/*.jar  # Add the JAR file to the staging area
        git commit -m "Add built JAR file"
        git pull origin build --rebase  # Pull changes from the remote 'build' branch
        git push origin build  # Push the changes to the 'build' branch
