name: Add Jars to Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List JAR files
        run: |
          find ./jar -name '*.jar' > jar_files.txt

      - name: Upload JARs to Release
        id: upload-release-assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./jar_files.txt
          asset_name: jar_files.txt
          asset_content_type: text/plain
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
