name: Add Jars to Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List JAR files
        run: |
          JAR_FILES=$(find ./jar -name '*.jar')
          echo "$JAR_FILES" > jar_files.txt

      - name: Upload JARs to Release
        run: |
          while IFS= read -r line; do
            echo "Uploading $line"
            curl -sSL -H "Authorization: Bearer $GITHUB_TOKEN" -H "Content-Type: application/zip" --data-binary @"$line" "$UPLOAD_URL?name=$(basename $line)"
          done < jar_files.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPLOAD_URL: ${{ github.event.release.upload_url }}
