name: Upload Release Assets

on:
  release:
    types: [created]

jobs:
  build:
    name: Upload JAR Files to Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List JAR files
        run: |
          jar_files=$(find ./jar -name '*.jar')
          for file in $jar_files; do
            echo "Uploading $file"
            curl -sSL \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: application/java-archive" \
              --data-binary @"$file" \
              "https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${GITHUB_EVENT_RELEASE}/assets?name=$(basename "$file")"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_RELEASE: ${{ github.event.release.id }}
